"""contenidos lenguajes y ejercicios

Revision ID: 002
Revises: 001
Create Date: 2026-07-16 16:23:54.947196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "002"
down_revision: str | None = "001"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("syntax_mode", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "slug", name="uq_language_institution_slug"),
    )
    op.create_index(
        op.f("ix_languages_institution_id"), "languages", ["institution_id"], unique=False
    )
    op.create_table(
        "exercises",
        sa.Column("language_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "true_false",
                "multiple_choice",
                "fill_code",
                "find_error",
                "trace_variables",
                "order_lines",
                "argued_response",
                name="exercise_type",
            ),
            nullable=False,
        ),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("origin", sa.Enum("teacher", "ai", name="exercise_origin"), nullable=False),
        sa.Column("status", sa.Enum("draft", "published", name="exercise_status"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercises_institution_id"), "exercises", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_exercises_language_id"), "exercises", ["language_id"], unique=False)
    op.create_table(
        "topics",
        sa.Column("language_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "level", sa.Enum("basico", "intermedio", "avanzado", name="topic_level"), nullable=False
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_topics_institution_id"), "topics", ["institution_id"], unique=False)
    op.create_index(op.f("ix_topics_language_id"), "topics", ["language_id"], unique=False)
    op.create_table(
        "topic_exercises",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id", "exercise_id", name="uq_topic_exercise"),
    )
    op.create_index(
        op.f("ix_topic_exercises_exercise_id"), "topic_exercises", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_exercises_topic_id"), "topic_exercises", ["topic_id"], unique=False
    )
    op.create_table(
        "topic_group_states",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("locked", "enabled", "evaluated", name="topic_group_state_value"),
            nullable=False,
        ),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduled_enable_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic_id", "group_id", name="uq_topic_group"),
    )
    op.create_index(
        op.f("ix_topic_group_states_group_id"), "topic_group_states", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_topic_group_states_topic_id"), "topic_group_states", ["topic_id"], unique=False
    )
    op.add_column(
        "groups",
        sa.Column("hide_locked_topics", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("groups", "hide_locked_topics", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "hide_locked_topics")
    op.drop_index(op.f("ix_topic_group_states_topic_id"), table_name="topic_group_states")
    op.drop_index(op.f("ix_topic_group_states_group_id"), table_name="topic_group_states")
    op.drop_table("topic_group_states")
    op.drop_index(op.f("ix_topic_exercises_topic_id"), table_name="topic_exercises")
    op.drop_index(op.f("ix_topic_exercises_exercise_id"), table_name="topic_exercises")
    op.drop_table("topic_exercises")
    op.drop_index(op.f("ix_topics_language_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_institution_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_exercises_language_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_institution_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_languages_institution_id"), table_name="languages")
    op.drop_table("languages")
    # ### end Alembic commands ###
