"""evaluaciones y motor de calificacion

Revision ID: 003
Revises: 002
Create Date: 2026-07-16 18:23:49.526260

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "003"
down_revision: str | None = "002"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluations",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("teacher_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("mode", sa.Enum("fixed", "cumulative", name="evaluation_mode"), nullable=False),
        sa.Column("up_to_topic_id", sa.UUID(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("is_ranked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["up_to_topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_group_id"), "evaluations", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_evaluations_institution_id"), "evaluations", ["institution_id"], unique=False
    )
    op.create_table(
        "practice_submissions",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("answer", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("needs_manual_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_practice_submissions_exercise_id"),
        "practice_submissions",
        ["exercise_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_submissions_group_id"), "practice_submissions", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_practice_submissions_institution_id"),
        "practice_submissions",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_practice_submissions_student_id"),
        "practice_submissions",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_attempts",
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("in_progress", "submitted", "expired", name="attempt_status"),
            nullable=False,
        ),
        sa.Column("total_score", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id", "student_id", name="uq_evaluation_attempt_student"),
    )
    op.create_index(
        op.f("ix_evaluation_attempts_evaluation_id"),
        "evaluation_attempts",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_attempts_institution_id"),
        "evaluation_attempts",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_attempts_student_id"),
        "evaluation_attempts",
        ["student_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_exercises",
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("exercise_version_at_attach", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evaluation_id", "exercise_id", name="uq_evaluation_exercise"),
    )
    op.create_index(
        op.f("ix_evaluation_exercises_evaluation_id"),
        "evaluation_exercises",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_exercises_exercise_id"),
        "evaluation_exercises",
        ["exercise_id"],
        unique=False,
    )
    op.create_table(
        "evaluation_answers",
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_exercise_id", sa.UUID(), nullable=False),
        sa.Column("answer", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("needs_manual_review", sa.Boolean(), nullable=False),
        sa.Column("manual_score", sa.Float(), nullable=True),
        sa.Column("reviewed_by_id", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["evaluation_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_exercise_id"],
            ["evaluation_exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", "evaluation_exercise_id", name="uq_answer_attempt_exercise"
        ),
    )
    op.create_index(
        op.f("ix_evaluation_answers_attempt_id"), "evaluation_answers", ["attempt_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_answers_evaluation_exercise_id"),
        "evaluation_answers",
        ["evaluation_exercise_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_evaluation_answers_evaluation_exercise_id"), table_name="evaluation_answers"
    )
    op.drop_index(op.f("ix_evaluation_answers_attempt_id"), table_name="evaluation_answers")
    op.drop_table("evaluation_answers")
    op.drop_index(op.f("ix_evaluation_exercises_exercise_id"), table_name="evaluation_exercises")
    op.drop_index(op.f("ix_evaluation_exercises_evaluation_id"), table_name="evaluation_exercises")
    op.drop_table("evaluation_exercises")
    op.drop_index(op.f("ix_evaluation_attempts_student_id"), table_name="evaluation_attempts")
    op.drop_index(op.f("ix_evaluation_attempts_institution_id"), table_name="evaluation_attempts")
    op.drop_index(op.f("ix_evaluation_attempts_evaluation_id"), table_name="evaluation_attempts")
    op.drop_table("evaluation_attempts")
    op.drop_index(op.f("ix_practice_submissions_student_id"), table_name="practice_submissions")
    op.drop_index(op.f("ix_practice_submissions_institution_id"), table_name="practice_submissions")
    op.drop_index(op.f("ix_practice_submissions_group_id"), table_name="practice_submissions")
    op.drop_index(op.f("ix_practice_submissions_exercise_id"), table_name="practice_submissions")
    op.drop_table("practice_submissions")
    op.drop_index(op.f("ix_evaluations_institution_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_group_id"), table_name="evaluations")
    op.drop_table("evaluations")
    # ### end Alembic commands ###
