"""agentes de ia skills y bandeja de aprobacion

Revision ID: 006
Revises: 005
Create Date: 2026-07-16 19:47:25.975276

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "006"
down_revision: str | None = "005"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_configs",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column(
            "agent_name",
            sa.Enum(
                "tutor",
                "exercise_generator",
                "grading_assistant",
                "learning_analytics",
                "code_integrity",
                name="agent_name",
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "agent_name", name="uq_agent_config_group"),
    )
    op.create_index(op.f("ix_agent_configs_group_id"), "agent_configs", ["group_id"], unique=False)
    op.create_table(
        "tutor_messages",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("student", "tutor", name="tutor_message_role"), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tutor_messages_exercise_id"), "tutor_messages", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_tutor_messages_group_id"), "tutor_messages", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_tutor_messages_institution_id"), "tutor_messages", ["institution_id"], unique=False
    )
    op.create_index(
        op.f("ix_tutor_messages_student_id"), "tutor_messages", ["student_id"], unique=False
    )
    op.create_table(
        "code_integrity_alerts",
        sa.Column("evaluation_answer_id", sa.UUID(), nullable=False),
        sa.Column("suspicious", sa.Boolean(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_answer_id"],
            ["evaluation_answers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_code_integrity_alerts_evaluation_answer_id"),
        "code_integrity_alerts",
        ["evaluation_answer_id"],
        unique=False,
    )
    op.add_column("evaluation_answers", sa.Column("ai_suggested_score", sa.Float(), nullable=True))
    op.add_column(
        "evaluation_answers", sa.Column("ai_suggested_justification", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluation_answers", "ai_suggested_justification")
    op.drop_column("evaluation_answers", "ai_suggested_score")
    op.drop_index(
        op.f("ix_code_integrity_alerts_evaluation_answer_id"), table_name="code_integrity_alerts"
    )
    op.drop_table("code_integrity_alerts")
    op.drop_index(op.f("ix_tutor_messages_student_id"), table_name="tutor_messages")
    op.drop_index(op.f("ix_tutor_messages_institution_id"), table_name="tutor_messages")
    op.drop_index(op.f("ix_tutor_messages_group_id"), table_name="tutor_messages")
    op.drop_index(op.f("ix_tutor_messages_exercise_id"), table_name="tutor_messages")
    op.drop_table("tutor_messages")
    op.drop_index(op.f("ix_agent_configs_group_id"), table_name="agent_configs")
    op.drop_table("agent_configs")
    # ### end Alembic commands ###
