"""progreso, insignias, periodos academicos y reportes

Revision ID: 007
Revises: 006
Create Date: 2026-07-16 21:25:36.536128

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "007"
down_revision: str | None = "006"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_periods",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_academic_periods_institution_id"),
        "academic_periods",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "badges",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "criteria",
            sa.Enum("topic_mastery", "language_mastery", "practice_streak", name="badge_criteria"),
            nullable=False,
        ),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("institution_id", "slug", name="uq_badge_institution_slug"),
    )
    op.create_index(op.f("ix_badges_institution_id"), "badges", ["institution_id"], unique=False)
    op.create_table(
        "report_jobs",
        sa.Column("requested_by_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("format", sa.Enum("xlsx", "pdf", name="report_format"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "done", "failed", name="report_status"),
            nullable=False,
        ),
        sa.Column("file_path", sa.String(length=500), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["academic_periods.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_jobs_group_id"), "report_jobs", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_report_jobs_institution_id"), "report_jobs", ["institution_id"], unique=False
    )
    op.create_table(
        "student_badges",
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("badge_id", sa.UUID(), nullable=False),
        sa.Column("language_id", sa.UUID(), nullable=True),
        sa.Column("topic_id", sa.UUID(), nullable=True),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "badge_id", "language_id", "topic_id", name="uq_student_badge_scope"
        ),
    )
    op.create_index(
        op.f("ix_student_badges_badge_id"), "student_badges", ["badge_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_badges_institution_id"), "student_badges", ["institution_id"], unique=False
    )
    op.create_index(
        op.f("ix_student_badges_student_id"), "student_badges", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_badges_student_id"), table_name="student_badges")
    op.drop_index(op.f("ix_student_badges_institution_id"), table_name="student_badges")
    op.drop_index(op.f("ix_student_badges_badge_id"), table_name="student_badges")
    op.drop_table("student_badges")
    op.drop_index(op.f("ix_report_jobs_institution_id"), table_name="report_jobs")
    op.drop_index(op.f("ix_report_jobs_group_id"), table_name="report_jobs")
    op.drop_table("report_jobs")
    op.drop_index(op.f("ix_badges_institution_id"), table_name="badges")
    op.drop_table("badges")
    op.drop_index(op.f("ix_academic_periods_institution_id"), table_name="academic_periods")
    op.drop_table("academic_periods")
    # ### end Alembic commands ###
