"""rag topic scope

Revision ID: 009
Revises: 008
Create Date: 2026-07-17 20:41:57.994944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "009"
down_revision: str | None = "008"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rag_documents", sa.Column("topic_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_rag_documents_topic_id"), "rag_documents", ["topic_id"], unique=False)
    op.create_foreign_key(
        "fk_rag_documents_topic_id_topics",
        "rag_documents",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_rag_documents_topic_id_topics", "rag_documents", type_="foreignkey")
    op.drop_index(op.f("ix_rag_documents_topic_id"), table_name="rag_documents")
    op.drop_column("rag_documents", "topic_id")
    # ### end Alembic commands ###
