"""planificador curricular

Revision ID: 010
Revises: 009
Create Date: 2026-07-18 01:37:08.584158

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "010"
down_revision: str | None = "009"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # Fase 15: nuevo valor del enum nativo de Postgres `agent_name` — alembic
    # autogenerate no detecta cambios de VALORES de un enum existente (solo
    # tablas/columnas nuevas), así que este ALTER TYPE se agrega a mano.
    # Seguro dentro de esta transacción porque el valor no se usa en la
    # misma migración (Postgres 12+ permite ADD VALUE en transacción,
    # siempre que no se use el valor todavía en esa misma transacción).
    # Nota: SQLAlchemy's `Enum(PyEnum)` persiste el *nombre* del miembro de
    # Python (p. ej. "curriculum_planner"), no su `.value` ("curriculum_
    # planning") — verificado con `enum_range` contra los valores ya
    # existentes (tutor, exercise_generator, ...) antes de escribir esto.
    op.execute("ALTER TYPE agent_name ADD VALUE 'curriculum_planner'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curriculum_plans",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("language_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("origin", sa.Enum("ai", "manual", name="curriculum_plan_origin"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "approved", "rejected", "superseded", name="curriculum_plan_status"),
            nullable=False,
        ),
        sa.Column(
            "kind", sa.Enum("initial", "replan", name="curriculum_plan_kind"), nullable=False
        ),
        sa.Column("source_syllabus", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_plans_group_id"), "curriculum_plans", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_curriculum_plans_institution_id"),
        "curriculum_plans",
        ["institution_id"],
        unique=False,
    )
    op.create_table(
        "curriculum_plan_items",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("period_id", sa.UUID(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("estimated_sessions", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["academic_periods.id"],
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["curriculum_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_curriculum_plan_items_plan_id"), "curriculum_plan_items", ["plan_id"], unique=False
    )
    op.add_column("topics", sa.Column("estimated_sessions", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Nota: Postgres no permite quitar un valor de un enum directamente, así
    # que 'curriculum_planning' se queda en el tipo `agent_name` tras un
    # downgrade — inofensivo (ningún dato lo referencia si esta migración
    # nunca llegó a usarse).
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topics", "estimated_sessions")
    op.drop_index(op.f("ix_curriculum_plan_items_plan_id"), table_name="curriculum_plan_items")
    op.drop_table("curriculum_plan_items")
    op.drop_index(op.f("ix_curriculum_plans_institution_id"), table_name="curriculum_plans")
    op.drop_index(op.f("ix_curriculum_plans_group_id"), table_name="curriculum_plans")
    op.drop_table("curriculum_plans")
    # ### end Alembic commands ###
