"""error_code y error_details en rubric_items y guides

Revision ID: 021
Revises: 020
Create Date: 2026-07-27 23:52:56.963564

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "021"
down_revision: str | None = "020"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("guides", sa.Column("error_code", sa.String(length=50), nullable=True))
    op.add_column("guides", sa.Column("error_details", sa.JSON(), nullable=True))
    op.add_column("rubric_items", sa.Column("error_code", sa.String(length=50), nullable=True))
    op.add_column("rubric_items", sa.Column("error_details", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rubric_items", "error_details")
    op.drop_column("rubric_items", "error_code")
    op.drop_column("guides", "error_details")
    op.drop_column("guides", "error_code")
    # ### end Alembic commands ###
