"""agrega ai_generated_feedback y exercise_versions

Revision ID: 877d0f5d3ae7
Revises: f5a6966ad920
Create Date: 2026-07-28 11:14:07.173146

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "877d0f5d3ae7"
down_revision: str | None = "f5a6966ad920"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_versions",
        sa.Column("exercise_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("institution_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercise_versions_exercise_id"), "exercise_versions", ["exercise_id"], unique=False
    )
    op.create_index(
        op.f("ix_exercise_versions_institution_id"),
        "exercise_versions",
        ["institution_id"],
        unique=False,
    )
    op.add_column(
        "evaluation_answers", sa.Column("ai_generated_feedback", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluation_answers", "ai_generated_feedback")
    op.drop_index(op.f("ix_exercise_versions_institution_id"), table_name="exercise_versions")
    op.drop_index(op.f("ix_exercise_versions_exercise_id"), table_name="exercise_versions")
    op.drop_table("exercise_versions")
    # ### end Alembic commands ###
