"""agrega request_id a error_logs

Revision ID: 944aaf3c8657
Revises: 023
Create Date: 2026-07-28 10:04:39.648858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "944aaf3c8657"
down_revision: str | None = "023"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("error_logs", sa.Column("request_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_error_logs_request_id"), "error_logs", ["request_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_error_logs_request_id"), table_name="error_logs")
    op.drop_column("error_logs", "request_id")
    # ### end Alembic commands ###
